spring:
  application:
    name: ASTronaut

  threads:
    virtual:
      enabled: true

  data:
    redis:
      port: 6379
      host: localhost
    web:
      pageable:
        serialization-mode: via_dto


  datasource:
    url: jdbc:postgresql://localhost:5432/ASTronaut?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true


jwt:
  secret: ${JWT_SECRET} #Your JWT Secret
  ttl: 3_000_000 #5 minutes
  refresh-before: 60000
  cookie-name: JWT_TOKEN
  cookie-max-age: 60 # 60 minutes
  cookie-http-only: true
  cookie-secure: false
  cookie-path: /


cache:
  principal:
    name: principalCache
    ttl: 30



