spring:
  application:
    name: ASTronaut

  data:
    redis:
      port: 6379
      host: localhost


  datasource:
    url: jdbc:postgresql://localhost:5432/ASTronaut
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true


jwt:
  secret: ${JWT_SECRET} #Your JWT Secret
  ttl: 300000 #5 minutes
  cookie-name: JWT_TOKEN
  cookie-max-age: 60 # 60 minutes
  cookie-http-only: true
  cookie-secure: false

cache:
  principal:
    name: principalCache
    ttl: 5



