spring:
  application:
    name: ASTronaut

  threads:
    virtual:
      enabled: true

  data:
    redis:
      port: 6379
      host: localhost
    web:
      pageable:
        serialization-mode: via_dto
  h2:
    console:
      enabled: true


  datasource:
    url: jdbc:postgresql://localhost:5432/ASTronaut?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true


jwt:
  secret: ${JWT_SECRET} #Your JWT Secret
  ttl: 1_000_000_000 #11 DAYS
  refresh-before: 60000
  cookie-name: JWT_TOKEN
  cookie-max-age: 60 # 60 minutes
  cookie-http-only: true
  cookie-secure: false
  cookie-path: /

cache:
  principal:
    name: principalCache
    ttl: 30

rate-limit:
  requests-per-minute: 500
  default-key-expiration: 100 # In minutes
  excluded-ips:
    - "0:0:0:0:0:0:0:1"
    - "127.0.0.1"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 9093

# Note that some of the excluded paths might feel redundant.
# They're not because custom filters don't support wildcards
security:
  excluded-paths:
    - "/"
    - "/index.html"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - "/api-docs"
    - "/swagger-ui.html"
    - "/css/header.css"
    - "/js/header.js"
    - "/css/toast.css"
    - "/js/toast.js"
    - "/auth.html"
    - "/auth/register"
    - "/auth/login"
    - "/auth/**"
    - "/swagger"
    - "/v3/api-docs"
  logout-url: "/users/logout"
  redirect-url: "/"
  clearAuth: true
  encodingStrength: 12 # password encoding strength

